version: "3.9"

services:
  unkey_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=dev
    ports:
      - 8080:8080
    
    environment:
      DATABASE_DSN: "${DATABASE_DSN}"
